/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.n1ppl3.thrift.kafka.jdbc.saver.entity;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TInstant implements org.apache.thrift.TBase<TInstant, TInstant._Fields>, java.io.Serializable, Cloneable, Comparable<TInstant> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TInstant");

    private static final org.apache.thrift.protocol.TField EPOCH_MILLIS_FIELD_DESC = new org.apache.thrift.protocol.TField("epochMillis", org.apache.thrift.protocol.TType.I64, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TInstantStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TInstantTupleSchemeFactory();

    public long epochMillis; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        EPOCH_MILLIS((short)1, "epochMillis");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch(fieldId) {
                case 1: // EPOCH_MILLIS
                    return EPOCH_MILLIS;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __EPOCHMILLIS_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.EPOCH_MILLIS, new org.apache.thrift.meta_data.FieldMetaData("epochMillis", org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TInstant.class, metaDataMap);
    }

    public TInstant() {
    }

    public TInstant(
            long epochMillis)
    {
        this();
        this.epochMillis = epochMillis;
        setEpochMillisIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public TInstant(TInstant other) {
        __isset_bitfield = other.__isset_bitfield;
        this.epochMillis = other.epochMillis;
    }

    public TInstant deepCopy() {
        return new TInstant(this);
    }

    @Override
    public void clear() {
        setEpochMillisIsSet(false);
        this.epochMillis = 0;
    }

    public long getEpochMillis() {
        return this.epochMillis;
    }

    public TInstant setEpochMillis(long epochMillis) {
        this.epochMillis = epochMillis;
        setEpochMillisIsSet(true);
        return this;
    }

    public void unsetEpochMillis() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EPOCHMILLIS_ISSET_ID);
    }

    /** Returns true if field epochMillis is set (has been assigned a value) and false otherwise */
    public boolean isSetEpochMillis() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EPOCHMILLIS_ISSET_ID);
    }

    public void setEpochMillisIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EPOCHMILLIS_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
        switch (field) {
            case EPOCH_MILLIS:
                if (value == null) {
                    unsetEpochMillis();
                } else {
                    setEpochMillis((java.lang.Long)value);
                }
                break;

        }
    }

    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case EPOCH_MILLIS:
                return getEpochMillis();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case EPOCH_MILLIS:
                return isSetEpochMillis();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that == null)
            return false;
        if (that instanceof TInstant)
            return this.equals((TInstant)that);
        return false;
    }

    public boolean equals(TInstant that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_epochMillis = true;
        boolean that_present_epochMillis = true;
        if (this_present_epochMillis || that_present_epochMillis) {
            if (!(this_present_epochMillis && that_present_epochMillis))
                return false;
            if (this.epochMillis != that.epochMillis)
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(epochMillis);

        return hashCode;
    }

    @Override
    public int compareTo(TInstant other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.valueOf(isSetEpochMillis()).compareTo(other.isSetEpochMillis());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetEpochMillis()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.epochMillis, other.epochMillis);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("TInstant(");
        boolean first = true;

        sb.append("epochMillis:");
        sb.append(this.epochMillis);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // alas, we cannot check 'epochMillis' because it's a primitive and you chose the non-beans generator.
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class TInstantStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public TInstantStandardScheme getScheme() {
            return new TInstantStandardScheme();
        }
    }

    private static class TInstantStandardScheme extends org.apache.thrift.scheme.StandardScheme<TInstant> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, TInstant struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true)
            {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // EPOCH_MILLIS
                        if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
                            struct.epochMillis = iprot.readI64();
                            struct.setEpochMillisIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            if (!struct.isSetEpochMillis()) {
                throw new org.apache.thrift.protocol.TProtocolException("Required field 'epochMillis' was not found in serialized data! Struct: " + toString());
            }
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, TInstant struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            oprot.writeFieldBegin(EPOCH_MILLIS_FIELD_DESC);
            oprot.writeI64(struct.epochMillis);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class TInstantTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public TInstantTupleScheme getScheme() {
            return new TInstantTupleScheme();
        }
    }

    private static class TInstantTupleScheme extends org.apache.thrift.scheme.TupleScheme<TInstant> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, TInstant struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            oprot.writeI64(struct.epochMillis);
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, TInstant struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            struct.epochMillis = iprot.readI64();
            struct.setEpochMillisIsSet(true);
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

